repos:
    - repo: https://github.com/astral-sh/ruff-pre-commit
      # Ruff version.
      rev: v0.8.6
      hooks:
          # Run the linter.
          - id: ruff
            args: [--fix, --config=./pyproject.toml]
          # Run the formatter.
          - id: ruff-format
            args: [--config=./pyproject.toml]
