name: Publish Python Package

on:
    release:
        types: [created]

jobs:
    increment-version:
        name: Bump version and commit changes
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4
              with:
                  ref: "main" # or your default branch
            - name: Bump project version
              run: |
                  # Extract version from the release
                  VERSION="${{ github.event.release.tag_name }}"
                  # Update the version in pyproject.toml
                  sed -i "s/^version = .*/version = \"$VERSION\"/" pyproject.toml
            - uses: EndBug/add-and-commit@v9
              name: Commit the version change
              with:
                  message: "Increment version to ${{ github.event.release.tag_name }}"
                  author_name: ${{ github.actor }}
                  author_email: ${{ github.actor }}@users.noreply.github.com

    publish:
        runs-on: ubuntu-latest
        needs: increment-version
        environment: release
        permissions:
            id-token: write
            contents: write
        steps:
            - uses: actions/checkout@v4
              with:
                  ref: "main"
                  fetch-depth: 0 # Ensure it fetches the latest commits
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"
                  cache: pip
                  cache-dependency-path: "**/pyproject.toml"
            - name: Install build dependencies
              run: pip install setuptools wheel build
            - name: Build package
              run: python -m build
            - name: Publish to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
